@startuml
package bp {

note as N1
<b>Main classes and methods for the <i>bp</i> package. This</b>
<b>is not an exhaustive list of everything,</b>
<b>just what you need to know to get started.</b>

The main classes, from client code point of view,
are <i>BProgram</i> and <i>BJavascriptProgram</i>.

They will be merged soon.
end note

package bprogram {
  class BProgram {
    + start()
  }
  class BJavascriptProgram
  note left: Has JS content

  class BThread
  note bottom: Has JS content

  class BSyncState {
    + statements
    + externalEvents
  }

  class RWBStatement

  package listenters {
    interface BProgramListener
    class InMemoryEventLogger ..|> BProgramListener
    class StreamLogger ..|> BProgramListener
  }

  BThread *--> "0..1" RWBStatement
  BProgram *--> "1..*" BThread
  BProgram *--> "1..*" BProgramListener: listeners
  BSyncState o--> "1..*" RWBStatement

}

package events {
  class BEvent
}


package eventsets {
  interface EventSet {
    contains(BEvent)
  }
  class ExplicitEventSet

  ExplicitEventSet ..|> EventSet
  ExplicitEventSet *--> "0..*" BEvent
}

package eventselection {
  interface EventSelectionStrategy {
    EventSelectionResult select(statements);
  }

  class SimpleEventSelectionStrategy
  class Selected {
    + event
  }

  class SelectedExternal {
    + index
  }

  class EventSelectionResult <<abstract>> {
    + accept( Visitor<R> ) : R
  }

  class Deadlock <<Singleton>>
  class NoneRequested <<Singleton>>
  
  class Selected --|> EventSelectionResult
  class SelectedExternal --|> Selected
  class Deadlock --|> EventSelectionResult
  class NoneRequested --|> EventSelectionResult

  SimpleEventSelectionStrategy ..|> EventSelectionStrategy
  EventSelectionStrategy ..>EventSelectionResult : <<creates>>
  EventSelectionStrategy ..>BSyncState : <<consumes>>
}

BProgram *--> EventSelectionStrategy: <<arbiter>>
BJavascriptProgram --|> BProgram
BEvent ..|> EventSet
RWBStatement *--> EventSet: WaitFor
RWBStatement *--> EventSet: Block
RWBStatement *--> ExplicitEventSet: Request
Selected o-->BEvent : selected event
}
@enduml
